const TYPES = {
	MailRepository: Symbol.for("MailRepository"),
	MailProvidersRepository: Symbol.for("MailProvidersRepository"),
	SendEmailUseCase: Symbol.for("SendEmailUseCase"),
	TrackEmailOpenUseCase: Symbol.for("TrackEmailOpenUseCase"),
	TypeORMMailRepository: Symbol.for("TypeORMMailRepository"),
	MailController: Symbol.for("MailController"),
	ClientRepository: Symbol.for("ClientRepository"),
	CreateClientUseCase: Symbol.for("CreateClientUseCase"),
	UpdateClientUseCase: Symbol.for("UpdateClientUseCase"),
	DeleteClientUseCase: Symbol.for("DeleteClientUseCase"),
	FindSinglePaginateUseCase: Symbol.for("FindSinglePaginateUseCase"),
	ClientController: Symbol.for("ClientController"),
	TemplateRepository: Symbol.for("TemplateRepository"),
	TemplateController: Symbol.for("TemplateController"),
	CreateTemplateUseCase: Symbol.for("CreateTemplateUseCase"),
	FindByIdTemplateUseCase: Symbol.for("FindByIdTemplateUseCase"),
	UpdateTemplateUseCase: Symbol.for("UpdateTemplateUseCase"),
	TemplateFindSinglePaginateUseCase: Symbol.for(
		"TemplateFindSinglePaginateUseCase",
	),
	DeleteTemplateUseCase: Symbol.for("DeleteTemplateUseCase"),
	AuthRepository: Symbol.for("AuthRepository"),
	RegisterUserUseCase: Symbol.for("RegisterUserUseCase"),
	AuthenticateUserUseCase: Symbol.for("AuthenticateUserUseCase"),
	AuthController: Symbol.for("AuthController"),
	UserRepository: Symbol.for("UserRepository"),
	CompanyRepository: Symbol.for("CompanyRepository"),
	CreateCompanyUseCase: Symbol.for("CreateCompanyUseCase"),
	UpdateCompanyUseCase: Symbol.for("UpdateCompanyUseCase"),
	DeleteCompanyUseCase: Symbol.for("DeleteCompanyUseCase"),
	CompanyController: Symbol.for("CompanyController"),
	FindByIdCompanyUseCase: Symbol.for("FindByIdCompanyUseCase"),
	FindByCNPJCompanyUseCase: Symbol.for("FindByCNPJCompanyUseCase"),
};

export { TYPES };
