services:
#  mailserver:
#    image: marcopas/docker-mailslurper
#    container_name: mailserver
#    restart: always
#    ports:
#      - "2500:2500"
#      - "8080:8080"
#      - "8085:8085"
#    networks:
#      - seneca_network

  postgres:
    image: postgres:latest
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - seneca_network

  redis:
    image: redis:latest
    container_name: rdcache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - seneca_network

volumes:
  postgres_data:

networks:
  seneca_network:
    driver: bridge
